import type { BusinessLead } from "@/types/business";

const now = new Date().toISOString();

export const mockBusinesses: BusinessLead[] = [
  {
    id: "fallback-cafe-olimpico-mile-end",
    name: "Cafe Olimpico",
    category: "Cafe",
    address: "124 Rue Saint-Viateur O, Montréal, QC",
    borough: "Mile End",
    phone: "+1 514-495-0746",
    website: "https://cafeolimpico.com",
    openingHours: null,
    email: null,
    emailSource: null,
    emailEnrichmentCheckedAt: null,
    latitude: 45.5234,
    longitude: -73.6016,
    osmUrl: "https://www.openstreetmap.org/search?query=Cafe%20Olimpico%20Montreal",
    notes: "",
    emailed: false,
    visited: false,
    leadStatus: "new",
    source: "OpenStreetMap",
    createdAt: now
  },
  {
    id: "fallback-crew-collective-old-montreal",
    name: "Crew Collective & Cafe",
    category: "Cafe",
    address: "360 Rue Saint-Jacques, Montréal, QC",
    borough: "Old Montreal",
    phone: "+1 514-285-7092",
    website: "https://crewcollectivecafe.com",
    openingHours: null,
    email: null,
    emailSource: null,
    emailEnrichmentCheckedAt: null,
    latitude: 45.5029,
    longitude: -73.5605,
    osmUrl: "https://www.openstreetmap.org/search?query=Crew%20Collective%20Cafe%20Montreal",
    notes: "",
    emailed: false,
    visited: false,
    leadStatus: "new",
    source: "OpenStreetMap",
    createdAt: now
  },
  {
    id: "fallback-foiegwa-griffintown",
    name: "Foiegwa",
    category: "Restaurant",
    address: "3001 Rue Notre-Dame O, Montréal, QC",
    borough: "Griffintown",
    phone: "+1 438-387-4252",
    website: "https://foiegwa.com",
    openingHours: null,
    email: null,
    emailSource: null,
    emailEnrichmentCheckedAt: null,
    latitude: 45.4798,
    longitude: -73.5762,
    osmUrl: "https://www.openstreetmap.org/search?query=Foiegwa%20Montreal",
    notes: "",
    emailed: false,
    visited: false,
    leadStatus: "new",
    source: "OpenStreetMap",
    createdAt: now
  },
  {
    id: "fallback-automne-rosemont",
    name: "Automne Boulangerie",
    category: "Bakery",
    address: "6500 Avenue Christophe-Colomb, Montréal, QC",
    borough: "Rosemont",
    phone: "+1 514-273-8889",
    website: "https://automneboulangerie.com",
    openingHours: null,
    email: null,
    emailSource: null,
    emailEnrichmentCheckedAt: null,
    latitude: 45.536,
    longitude: -73.5995,
    osmUrl: "https://www.openstreetmap.org/search?query=Automne%20Boulangerie%20Montreal",
    notes: "",
    emailed: false,
    visited: false,
    leadStatus: "new",
    source: "OpenStreetMap",
    createdAt: now
  },
  {
    id: "fallback-arthurs-saint-henri",
    name: "Arthur's Nosh Bar",
    category: "Restaurant",
    address: "4621 Rue Notre-Dame O, Montréal, QC",
    borough: "Saint-Henri",
    phone: "+1 514-757-5190",
    website: "https://arthursmtl.com",
    openingHours: null,
    email: null,
    emailSource: null,
    emailEnrichmentCheckedAt: null,
    latitude: 45.4737,
    longitude: -73.5866,
    osmUrl: "https://www.openstreetmap.org/search?query=Arthur%27s%20Nosh%20Bar%20Montreal",
    notes: "",
    emailed: false,
    visited: false,
    leadStatus: "new",
    source: "OpenStreetMap",
    createdAt: now
  }
];
