import type { BusinessLead } from "@/types/business";

const now = new Date().toISOString();

export const mockBusinesses: BusinessLead[] = [
  {
    id: "mock-cafe-olympico-mile-end",
    name: "Café Olimpico",
    category: "Cafe",
    address: "124 Rue Saint-Viateur O, Montréal, QC",
    borough: "Mile End",
    phone: "+1 514-495-0746",
    website: "https://cafeolimpico.com",
    openingHours: ["Mon-Sun: 7:00 AM – 11:00 PM"],
    rating: 4.6,
    googleMapsUrl: "https://maps.google.com/?q=Cafe+Olimpico+Montreal",
    businessStatus: "OPERATIONAL",
    email: null,
    notes: "Good fit for premium coffee equipment partnerships.",
    leadStatus: "new",
    source: "Mock Data",
    createdAt: now
  },
  {
    id: "mock-crew-collective-old-montreal",
    name: "Crew Collective & Café",
    category: "Coffee Shop",
    address: "360 Rue Saint-Jacques, Montréal, QC",
    borough: "Old Montreal",
    phone: "+1 514-285-7092",
    website: "https://crewcollectivecafe.com",
    openingHours: ["Mon-Fri: 8:00 AM – 4:00 PM", "Sat-Sun: 9:00 AM – 5:00 PM"],
    rating: 4.4,
    googleMapsUrl: "https://maps.google.com/?q=Crew+Collective+Cafe+Montreal",
    businessStatus: "OPERATIONAL",
    email: null,
    notes: "",
    leadStatus: "contacted",
    source: "Mock Data",
    createdAt: now
  },
  {
    id: "mock-foiegwa-griffintown",
    name: "Foiegwa",
    category: "Brunch Restaurant",
    address: "3001 Rue Notre-Dame O, Montréal, QC",
    borough: "Griffintown",
    phone: "+1 438-387-4252",
    website: "https://foiegwa.com",
    openingHours: ["Mon-Sun: 9:00 AM – 11:00 PM"],
    rating: 4.5,
    googleMapsUrl: "https://maps.google.com/?q=Foiegwa+Montreal",
    businessStatus: "OPERATIONAL",
    email: null,
    notes: "Check decision maker before outreach.",
    leadStatus: "qualified",
    source: "Mock Data",
    createdAt: now
  },
  {
    id: "mock-automne-plateau",
    name: "Automne Boulangerie",
    category: "Bakery",
    address: "6500 Ave Christophe-Colomb, Montréal, QC",
    borough: "Rosemont",
    phone: "+1 514-273-8889",
    website: "https://automneboulangerie.com",
    openingHours: ["Wed-Sun: 8:00 AM – 4:00 PM"],
    rating: 4.8,
    googleMapsUrl: "https://maps.google.com/?q=Automne+Boulangerie+Montreal",
    businessStatus: "OPERATIONAL",
    email: null,
    notes: "",
    leadStatus: "new",
    source: "Mock Data",
    createdAt: now
  },
  {
    id: "mock-arthurs-verdun",
    name: "Arthur's Nosh Bar",
    category: "Restaurant",
    address: "4621 Notre-Dame St W, Montréal, QC",
    borough: "Verdun",
    phone: "+1 514-757-5190",
    website: "https://arthursmtl.com",
    openingHours: ["Thu-Mon: 9:00 AM – 3:00 PM"],
    rating: 4.6,
    googleMapsUrl: "https://maps.google.com/?q=Arthurs+Nosh+Bar+Montreal",
    businessStatus: "OPERATIONAL",
    email: null,
    notes: "",
    leadStatus: "new",
    source: "Mock Data",
    createdAt: now
  }
];
